### PR TITLE
Merge fabric@1.7.19 with passing travis build

### PR DESCRIPTION
**Pull request by saifelse**
- Merge in fabric@1.7.19 which is the latest 1.x version of fabric
- Re-introduce canvas, jsdom, and xmldom as devDependencies
  so that the test suite can be run on Travis CI

### CODE REVIEW

**Comment by saifelse** [comment]
Travis build: https://travis-ci.org/saifelse/fabric-browseronly
@jacob-beltran : if this is merged in, it would be nice to enable Travis from https://travis-ci.org/jacob-beltran/fabric-browseronly

**Comment by jacob-beltran** [comment]
Man, thanks so much for this. I haven't had time to keep this up to date. The PR is much appreciated.

**Comment by saifelse** [comment]
@jacob-beltran : no problem, and thanks for the speedy accept! Would you mind publishing to npm?  Giddy to use this in production! 😁

**Comment by jacob-beltran** [comment]
@saifelse Just published v1.17.19 https://www.npmjs.com/package/fabric-browseronly
Thanks so much for your help!!

**Pull request merged**
